#!/bin/sh

# Munin plugin displaying dnsmasq cache hits / misses

# To signal dnsmasq to dump cache stats to it's log, as root,
# crontab -e
# */5  *  *   *     *    killall -10 dnsmasq

# Output graph config if script is called with parameter "config"
case $1 in
   config)
        cat <<'EOM'
graph_title dnsmasq cache hits / misses
graph_info Displays details of dnsmasq caching
graph_vlabel cache misses (-ve) / hits (+ve)
graph_category network
cachemisses.label cache misses
cachemisses.info Number of unsuccessful cache look ups.
cachehits.label cache hits
cachehits.info Number of successful cache look ups.
EOM
        exit 0;;
esac

# Output graph details if script is called with no parms
tac /var/log/dnsmasq.log | awk -F "[ \t\n/,]+" '/queries forwarded/ { print "cachemisses.value -"$7"\ncachehits.value "$11; exit; }'
